### ISSUE TITLE
Boost Slow in API Response Causing Lotus-miner Info Command Timeout

### ISSUE THREAD

**Issue by William8Work** [filecoin-project/boost#1193] opened 2023-02-16 16:36 UTC
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature or enhancement request. If it is, please open a [new idea discussion](https://github.com/filecoin-project/boost/discussions/new?category=ideas) instead. New feature and enhancement requests would be entertained by the boost team after a thorough discussion only.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to boost.

### Boost component

- [X] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
boostd version 1.5.1-rc2+git.2c5604e
boost version 1.5.1-rc2+git.2c5604e
```

### Describe the Bug

once a while, the lotus-miner info command errors out on getting information back from boost API. 

`Lotus-miner info command`

```
Workers: Seal(10) WdPoSt(0) WinPoSt(0)
ERROR: %!s(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
```

### Logging Information

```text
whenever that lotus-miner info command erroring out, there is a corresponding error entry in boost log:


Boost log:
2023-02-14T10:55:05.891-0800    ERROR   rpc     go-jsonrpc@v0.0.0-20221118154859-f3f8e9b1cb11/websocket.go:129  handle me:writev tcp4 10.1.18.168:8787->10.1.18.180:45346: writev: connection reset by peer
```
```


### Repo Steps

This happens frequently when both miner and boost are stopped, then restart miner, once it's up and running, start boostd. And then execute the command lotus-miner info.

This also happens once a while when both lotus-miner and boost are running fine, workload are light (no sealing activities). 
...

**Comment by LexLuthr** [comment] 2023-02-16 16:38
@William8Work Can you reproduce this on the latest stable release v1.5.1? I think we pushed a few changes around these nil pointer issue.

**Comment by namoo-cloud** [comment] 2023-02-22 10:35
lotus-miner info

**Comment by dirkmc** [comment] 2023-02-27 10:06
> ERROR: %!s(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)

The error message is printed out by [lotus cli helper](https://github.com/filecoin-project/lotus/blob/0c9f697bf611ad3a513d051a41e1288fa8859594/cli/helper.go#L52) when an error is returned from a CLI Action:
```
fmt.Fprintf(os.Stderr, "ERROR: %s\n\n", err)
```

The format of the error message `%!s(PANIC=...nil pointer` indicates that fmt.Fprintf encountered a nil pointer when trying to call the `Error()` method on the golang `error` object that was passed to it. This is most likely because the `error` object wraps a nil error. An example golang Test that reproduces this behaviour:
```
type myerr struct {
	err error
}

func (e *myerr) Error() string {
	// if e.err is nil, this will panic
	return e.err.Error()
}

func TestPrintErr(t *testing.T) {
	fmt.Printf("%s\n", &myerr{})
}

=== RUN   TestPrintErr
%!s(PANIC=Error method: runtime error: invalid memory address or nil pointer dereference)
--- PASS: TestPrintErr (0.00s)
```

I'm reassigning this bug to go-jsonrpc because it looks like the underlying implementation of go-jsonrpc is returning an error object that wraps a nil error.

**Comment by dirkmc** [comment] 2023-02-28 08:37
Added an issue to the lotus repo to [Remove markets API calls from lotus-miner info](https://github.com/filecoin-project/lotus/issues/10362#top)

**Comment by dirkmc** [comment] 2023-03-01 09:06
I opened https://github.com/filecoin-project/go-jsonrpc/issues/96 to track the underlying go-jsonrpc issue.
https://github.com/filecoin-project/lotus/pull/10364 takes care of this issue in lotus.

**Closed by dirkmc** 2023-03-01 09:06 UTC
Labels: kind/bug, need/triage
