### ISSUE TITLE
legacy format deals without unsealed copy fails during recovery process

### ISSUE THREAD

**Issue by honghaoq** [filecoin-project/boost#690] opened 2022-08-05 19:15 UTC
PiKNiK reported that indexing for renewed deals (the old format deals using graphsync) seem to be failing, while the new boost format deals seem to be working fine with indexing.
For old deals, those ones without an unsealed sector, they try to recover it and the miner tries to unseal the copy, but the formatting is incompatible with that indexing function with the following error:
failed to read/generate CAR Index: invalid header: malformed stream: invalid appearance of int token; expected start of map
The impact is currently they have more than 600 old deals unable to index today because of this. This seems to be happening for other SPs too and impacting indexing for thousands of renewed deals.

https://filecoinproject.slack.com/archives/C02T827T9N0/p1655945945995169

**Comment by jacobheun** [comment] 2022-11-25 13:55
Duplicate of https://github.com/filecoin-project/boost/issues/613

**Closed by jacobheun** 2022-11-25 13:55 UTC
Labels: kind/bug, area/retrieval, area/indexing
