### ISSUE TITLE
Boost deals stuck at "failed to add index and announce deal"

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/boost#1273] opened 2023-03-14 00:10 UTC
### Checklist

- [X] This is **not** a question or a support request. If you have any boost related questions, please ask in the [discussion forum](https://github.com/filecoin-project/boost/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/boost/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/boost/issues) and the [discussion forum](https://github.com/filecoin-project/boost/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/boost/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to boost.

### Boost component

- [ ] boost daemon - storage providers
- [ ] boost client
- [ ] boost UI
- [ ] boost data-transfer
- [ ] boost index-provider
- [ ] Other

### Boost Version

```text
1.6.0
```

### Describe the Bug

I occasionally see a bunch of deals in this state;
```
Paused at 'Announcing': failed to add index and announce deal: failed to register deal with dagstore: failed to register shard: failed to read/generate CAR Index: error reading car header: getting backing reader: getting reader at +0: non-200 code: 500
```

when I click the "retry" button it almost instantly goes to "proving"
Can this be automated?

Might be related: https://github.com/filecoin-project/boost/issues/664

### Logging Information

```text
155297-{"level":"debug","ts":"2023-03-01T01:45:24.278Z","logger":"dagstore","caller":"dagstore@v0.5.5/dagstore_control.go:64","msg":"processing task","op":"OpShardFail","shard":"baga6ea4seaqm4xiwb6owue6sfh3buuf2ix5nnmx5vus6hsirldf6euiovjawqja","error":"failed to read/generate CAR Index: error reading car header: getting backing reader: getting reader at +0: non-200 code: 500"}
155298-{"level":"debug","ts":"2023-03-01T01:45:24.278Z","logger":"dagstore","caller":"dagstore/wrapper.go:169","msg":"trace","shard-key":"baga6ea4seaqdcccgwuexbr63xq2xnfnmh4zj6onjhjjnfw6ombtn6vk55vhb2py","op-type":"OpShardFail","after":"ShardStateErrored"}
155299:{"level":"info","ts":"2023-03-01T01:45:24.278Z","logger":"boost-storage-deal","caller":"logs/log.go:40","msg":"deal paused because of recoverable error","id":"f8c26790-4b60-4a6d-93be-aa0b7790f700","err":"failed to add index and announce deal: failed to register deal with dagstore: failed to register shard: failed to read/generate CAR Index: error reading car header: getting backing reader: getting reader at +0: non-200 code: 500","checkpoint":"AddedPiece","retry":"auto"}
155300-{"level":"info","ts":"2023-03-01T01:45:24.278Z","logger":"dagstore","caller":"dagstore@v0.5.5/handlers.go:36","msg":"failure handler: recovering shard","key":"baga6ea4seaqm4xiwb6owue6sfh3buuf2ix5nnmx5vus6hsirldf6euiovjawqja","from_error":"failed to read/generate CAR Index: error reading car header: getting backing reader: getting reader at +0: non-200 code: 500","attempt":0}
155301-{"level":"debug","ts":"2023-03-01T01:45:24.278Z","logger":"dagstore","caller":"dagstore@v0.5.5/dagstore_control.go:327","msg":"will write trace to the trace channel","shard":"baga6ea4seaqm4xiwb6owue6sfh3buuf2ix5nnmx5vus6hsirldf6euiovjawqja"}
155302-{"level":"debug","ts":"2023-03-01T01:45:24.278Z","logger":"dagstore","caller":"dagstore@v0.5.5/dagstore_control.go:338","msg":"finished writing trace to the trace channel","shard":"baga6ea4seaqm4xiwb6owue6sfh3buuf2ix5nnmx5vus6hsirldf6euiovjawqja"}
```

### Repo Steps

1. Run boost and import deals
2. See issue

![image](https://user-images.githubusercontent.com/1442796/224859177-935ac0ec-14da-4dd4-8804-7a92e3481a3b.png)

**Comment by jacobheun** [comment] 2023-03-14 10:53
Yeah we should put this into an auto retry with a backoff. It looks like there's probably a temporary jsonRPC error reading the data for indexing.

**Comment by dirkmc** [comment] 2023-03-14 13:40
I'm not sure a retry is the right solution - really we should figure out why the underlying error happens in the first place and fix that

**Comment by RobQuistNL** [comment] 2023-03-20 18:46
I'll try when I see it happen again

**Comment by beck-8** [comment] 2023-03-24 06:43
related: https://github.com/filecoin-project/boost/issues/920

**Comment by beck-8** [comment] 2023-03-24 06:44
I often run into this problem and have to wait for it to recover slowly by itself, reading a lot of data from persistent storage in the meantime.

**Comment by johansealstorage** [comment] 2023-03-29 11:50
I also hit this issue on our side.  
Also managed to re-produce on our devnet side with the workers and boost networks slowed down a bit using traffic control.  
I'm not seeing anything too obvious in the miner logs though.

**Comment by johansealstorage** [comment] 2023-03-29 12:03
And if you accidentally click on the X instead of the > button, the deal is "Error: user manually terminated the deal" without any prompt or warning.

**Comment by LexLuthr** [comment] 2023-03-29 13:40
@johansealstorage I would need full logs from miner/boost/daemon if you are able to reproduce.

**Comment by johansealstorage** [comment] 2023-03-30 10:00
![image](https://user-images.githubusercontent.com/97198074/228801201-e31aded7-36ec-41ed-911e-384f128790b1.png)

This is a screenshot of what Boost looks like on my side on devnet doing a batch of a 1000 deals

**Comment by johansealstorage** [comment] 2023-03-30 10:20
@LexLuthr , I send the logs to you on Slack in a pm.

**Comment by johansealstorage** [comment] 2023-03-30 11:54
Just for interest sake, I'm using this query to unpause these deals in bulk on Boost: 

`for myid in `curl -X POST -H "Content-Type: application/json" -d '{"query":"query { deals(limit: 10000) { deals { ID CreatedAt Message } } }"}' http://localhost:8080/graphql/query | jq -r '.data.deals.deals[] | select(.Message | startswith("Paused")) | .ID'`; do curl -X POST -H "Content-Type: application/json" -d '{"query":"mutation { dealRetryPaused(id: \"'$myid'\") }"}' http://localhost:8080/graphql/query; echo Unpaused $myid; done
`

**Comment by LexLuthr** [comment] 2023-04-05 09:27
@johansealstorage Are you able to index and announce these deals after retry?
I am seeing similar errors as below in the log file you sent me. This looks like a malformed car or incorrect header. All of your failures have similar logs. I did not find any logs with `getting backing reader: getting reader at +0: non-200 code: 500` error. I would request you to check with your client about these deals.  

`{"log":"2023-03-30T09:57:35.241Z\u0009INFO\u0009boost-storage-deal\u0009logs/log.go:40\u0009deal paused because of recoverable error\u0009{\"id\": \"819622e5-992c-4f10-9f77-0ae95bad9c70\", \"err\": \"failed to add index and announce deal: failed to register deal with dagstore: failed to register shard: failed to read/generate CAR Index: expected 1 as the cid version number, got: 2089\", \"checkpoint\": \"AddedPiece\", \"retry\": \"auto\"}\n","stream":"stderr","time":"2023-03-30T09:57:35.241740223Z"}`

**Comment by thatch45** [comment] 2023-04-05 23:12
I am also getting a ton of these:
```
Paused at 'Announcing': failed to add index and announce deal: failed to register deal with dagstore: failed to register shard: failed to read/generate CAR Index: error reading car header: getting backing reader: getting reader at +0: non-200 code: 500
```
[boostd_tail.log](https://github.com/filecoin-project/boost/files/11163912/boostd_tail.log)

**Comment by LexLuthr** [comment] 2023-04-05 23:46
@thatch45 I need logs from miner side. Please get the logs from the time duration when this error occurs.

**Comment by jcace** [comment] 2023-04-08 01:04
I'm seeing these from time to time too. Seems to be random

**Comment by LexLuthr** [comment] 2023-04-10 08:59
Update:
1. We request the piece reader from the miner (via dagstore). This request is successful.
2. But when we try to seek the piece, we run into this error. (We are trying to find the car header)
3. It looks like miner supplies a reader which is not ready. 

I have asked @TippyFlitsUK to help with this issue from Lotus side as we strongly suspect that problem is on that side.

**Comment by brendalee** [comment] 2023-06-29 22:25
@LexLuthr @TippyFlitsUK any update on this?

**Comment by LexLuthr** [comment] 2023-06-30 03:20
@brendalee I think we can folow up on this after LID. Since, we went to PieceReader via dagstore earlier, it was hard to surface up the errors. Once dagstore is out of the picture, we should at least have a better understanding of what might be wrong if this error reoccurs. 
I have not seen any recent reports of this.

**Comment by hyunmoon** [comment] 2023-09-29 15:21
![image](https://github.com/filecoin-project/boost/assets/2242149/bf0beb64-d543-45ff-a4de-f865582bd6a4)

I think for every 100 deals I onboard, I encounter at least one or two of these errors.
A monotonous part of my daily routine involves repeatedly clicking the retry button, much like a robot.

**Comment by brendalee** [comment] 2023-09-29 15:51
@hyunmoon - thanks for the input. have you upgraded to Boost v2 yet? We've made some significant improvements that will reduce a lot of these problems.

**Comment by hyunmoon** [comment] 2023-09-29 18:13
I haven't yet, but given this compelling reason, I believe I will now. Thanks for the information.

**Comment by LexLuthr** [comment] 2023-10-02 07:40
I am closing this issue as complete. The Dagstore is no longer a part of the Boost V2. If you are experiencing similar symptoms in Boost v1, please upgrade to v2. If you are already on v2 and are seeing this problem, please open a new issue.

**Closed by LexLuthr** 2023-10-02 07:40 UTC
Labels: area/ux, kind/bug, area/deals, need/triage
