### ISSUE TITLE
Basic perf testing for LID

### ISSUE THREAD

**Issue by brendalee** [filecoin-project/boost#1415] opened 2023-05-03 19:28 UTC
Placeholder for testing for retrievals with LID. Mostly, ensure there is no regression. 

- Perform retrieval for a piece with many blocks, on bitswap, http, and graphsync

**Comment by brendalee** [comment] 2023-06-01 22:40
@nonsense - can you update what results we have with sofiaminer and filcollins when you get a chance? thank you!

**Comment by nonsense** [comment] 2023-06-22 14:29
I performed basic testing of graphsync retrieval with `lotus client retrieve` as well as piece retrieval with booster-http.

Piece retrieval with booster-http performed well with >1Gbps speeds on filcollins.

Graphsync retrieval was performing with its usual speed of a few MiBs per second.

There are a few regressions in the monitoring setup, so it was hard to build up a complete trace of graphsync requests -

1. All the traces are flattened out and not respecting the root context trace ID.
2. Grafana/Tempo setup is having a degraded search, probably due to one of the latest updates.

---

Overall I didn't find any blocking regressions, but we found a few issues that need further investigation:
- The `Blockstore` that Graphsync uses appears to be the same as the one that Bitswap uses, meaning that all Graphsync requests turn into individual Blockstore.Get requests, which is incorrect, as we lose context around the `piececid` and piece reader.
- From a monitoring perspective it appears we no longer have working code to follow easily a single graphsync request with all its concurrency span-out traces, so it is hard to reason about the correctness of the request.

cc @dirkmc @LexLuthr

**Comment by dirkmc** [comment] 2023-06-28 10:29
I performed testing of bitswap retrieval using `booster-bitswap fetch with concurrency factor of 10 over the local network interface`.
```
2023-06-28T13:23:34.624+0300 fetch
{"cid": "QmZ8awuqbP27xW7q7KfBhx4YozMXuumFFnZBgiVHfa34Vm", "concurrency": 10}

2023-06-28T13:23:53.190+0300 fetch complete
{"count": 3004, "size": 774376960, "duration": "18.565761502s"}
```

booster-bitswap was able to serve 738MiB in 18.6s: 41MiB/s

**Comment by dirkmc** [comment] 2023-06-28 10:46
The results of basic performance testing are acceptable for http, bitswap and graphsync.
Therefore I'm closing out this ticket. I will added follow up tickets for the points Anton mentioned above:
- [LID performance improvement: create index for graphsync request](https://github.com/filecoin-project/boost/issues/1541#top)
- [LID: Fix graphsync request span-out traces](https://github.com/filecoin-project/boost/issues/1542#top)

**Closed by dirkmc** 2023-06-28 10:46 UTC
